site_name: LightGraphs.jl
site_author: Seth Bromberger
repo_url: https://github.com/JuliaGraphs/LightGraphs.jl/
theme: readthedocs
pages:
  - 'Home': '_generated/index.md'
  - 'About': '_generated/about.md'
  - 'Getting Started': '_generated/gettingstarted.md'
  - 'Operators': '_generated/operators.md'
  - 'Path and Traversal': '_generated/pathing.md'
  - 'Distance': '_generated/distance.md'
  - 'Centrality measures': '_generated/centrality.md'
  - 'Linear Algebra': '_generated/linalg.md'
  - 'Graph Generators': '_generated/generators.md'
  - 'Reading / Writing Graphs': '_generated/persistence.md'
  - 'Integration with other packages': '_generated/integration.md'
docs_dir: 'doc'
markdown_extensions:
  - extra
  - tables
  - fenced_code
extra_css:
  - LightGraphs.css
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
